/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.samplegame;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.util.Random;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author com4936
 */
public class Game1 extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form Game1
     */
    Image image;
    int x = 10;
    int y = 640;
    int x2,y2;
    int count = 0;
    Clip clip;
    
    public Game1() {
        initComponents();
        setSize(700,700);
        setTitle("เกมต่างๆ");
        image =Toolkit.getDefaultToolkit().createImage("..\\picture\\picture (2).jpg");
        this.addKeyListener(this);
        createBox();
    }

    public void createBox(){
        Random random = new Random();
        x2 = random.nextInt(getWidth()-60);
        y2 = random.nextInt(getHeight()-60);
        createSound();
    }
    
    public void createSound(){
        try
        {
            File soundFile = new File("..\\img\\SoundTrue.wav");
            AudioInputStream adioIn = AudioSystem.getAudioInputStream(soundFile);
            clip = AudioSystem.getClip();
            clip.open(adioIn);
        }catch(Exception ex){}
    }
    
    public void paint(Graphics g){
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, super.getWidth(), super.getHeight());
        g.drawImage(image,x,y,50,50, this);
        
        g.setColor(Color.red);
        g.fillRect(x2, y2, 50, 50);
        
        g.setColor(Color.BLACK);
        g.setFont(new Font("Angsana new", Font.BOLD, 60));
        g.drawString("score " + count ,50, 100);
        
        if(count >= 10){
            g.setColor(Color.GRAY);
            g.fillRect(0, 0, super.getWidth(), super.getHeight());
            g.setColor(Color.RED);
            g.setFont(new Font("Angsana new", Font.BOLD, 90));
            g.drawString("THE WINNER",((super.getWidth()-350)/2), (super.getHeight()/2));
        }
    }
    
    public void checkCollission(){
        Rectangle rPlayer = new Rectangle(x,y,50,50);
        Rectangle rBox = new Rectangle(x2,y2,50,50);
        if(count <10){
            if(rPlayer.intersects(rBox)){
                //System.out.println("Collised");
                clip.loop(0);
                createBox();
                count = count+5;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game1().setVisible(true);
            }
        });
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        //System.out.println(ke.getKeyCode());
        if(count <10){
        switch(ke.getKeyCode()){
            case 39:
                if(x < getWidth()-60)
                {
                    x=x+10;
                    repaint();
                }
                break;
            case 37:
                if(x > 10)
                {
                    x=x-10;
                    repaint();
                }
                break;
            case 38:
                if(y > 30)
                {
                    y=y-10;
                    repaint();
                }
                break;
            case 40:
                if(y < getHeight()-60)
                {
                    y=y+10;
                    repaint();
                }
                break;
        }
        checkCollission();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
