/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.graphicdemo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author com4936
 */
public class AutoMovePicture extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form AutoMovePicture
     */
    Image image;
    int size = 100;
    int x = 0;
    int y = 30;
    int n = 1;
    int count = 0;
    
    
    public AutoMovePicture() {
        initComponents();
        image=Toolkit.getDefaultToolkit().createImage("G:\\img\\picture (6).jpg");
        super.setSize(700,700);
        new Thread(this).start();
    }
    
    public void paint(Graphics g){
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, super.getWidth(), super.getHeight());
        g.drawImage(image, x, y,size,size, this);
    }
    
    @Override
    public void run() {
        while(true){
            try {
                Thread.sleep(50);
            } catch (InterruptedException ex) {
                Logger.getLogger(AutoMovePicture.class.getName()).log(Level.SEVERE, null, ex);
            }
            switch(n){
                    case 1 : 
                        if(x<=600)
                        {
                            x=x+10;
                            repaint();
                        }
                        if(x>=600)
                        {
//                            if(count  >= 1)
//                            {
//                                x=x-(50*(count+1));
//                            }
                            n=2;
                        };
                         break;
                    case 2 : 
                        if(y<=600)
                        {
                            y=y+10;
                            repaint();
                        }
                        if(y>=600)
                        {
//                            if(count >= 1)
//                            {
//                                y=y-(50*(count+1));
//                            }
                            n=3;
                        };
                        break;
                    case 3 :  
                        if(x>=0)
                        {
                            x=x-10;
                            repaint();
                        }
                        if(x<=0)
                        {
//                            if(count >= 1)
//                            {
//                                x=x+(50*(count+1));
//                            }
                            n=4;
                        };
                        break;
                    case 4 : 
                        if(y>=30)
                        {
                            y=y-10;
                            repaint();
                        }
                        if(y<=30)
                        {
//                            y=y+(50*(count+1));
//                            count = count + 1;
                            n=1;

                        };
                        break;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoMovePicture");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoMovePicture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoMovePicture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoMovePicture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoMovePicture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoMovePicture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
