/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.graphicdemo;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author WONG-PC
 */
public class GraphicTest3 extends javax.swing.JFrame {

    /**
     * Creates new form GraphicTest3
     */
    public GraphicTest3() {
        initComponents();
        setSize(600,600);
    }
    public void paint(Graphics g){
        super.setSize(600, 700);
        
        g.setColor(Color.WHITE);
        g.fillRect(0,0,getWidth(), getHeight());
        
        //เส้น
        g.setColor(new Color(255, 32, 78));
        g.drawLine(110, 125, 500, 125);
        g.drawLine(110, 150, 500, 150);
        g.drawLine(110, 175, 500, 175);
        g.drawLine(110, 200, 500, 200);
        g.drawLine(110, 225, 500, 225);
        g.drawLine(110, 250, 500, 250);
        g.drawLine(110, 275, 500, 275);
        g.drawLine(110, 300, 500, 300);
        g.drawLine(110, 325, 500, 325);
        g.drawLine(110, 350, 500, 350);
        g.drawLine(110, 375, 500, 375);
        g.drawLine(110, 400, 500, 400);
        g.drawLine(110, 425, 500, 425);
        g.drawLine(110, 450, 500, 450);
        g.drawLine(110, 475, 500, 475);
        g.drawLine(110, 500, 500, 500);
        g.drawLine(110, 525, 500, 525);
        g.drawLine(110, 550, 500, 550);
        g.drawLine(110, 575, 500, 575);
        g.drawLine(110, 600, 500, 600);
        g.setColor(new Color(160, 21, 62));
        g.drawLine(110, 625, 510, 625);
        g.drawLine(110, 105, 110, 625);
        
        //แท่ง
        g.setColor(new Color(180, 63, 63));
        g.fillRect(130, 350, 50, 275);
        
        g.setColor(new Color(255, 130, 37));
        g.fillRect(190, 325, 50, 300);
        
        g.setColor(new Color(108, 148, 111));
        g.fillRect(250, 250, 50, 375);
        
        g.setColor(new Color(145, 79, 30));
        g.fillRect(310, 225, 50, 400);
        
        g.setColor(new Color(15, 103, 177));
        g.fillRect(370, 150, 50, 475);
        
        g.setColor(Color.BLACK);
        g.fillRect(430, 375, 50, 250);
        
        //ข้อมูล
        g.setFont(new Font("TH SarabunPSK", Font.PLAIN, 18));
        
        g.setColor(Color.BLACK);
        g.drawString("10,000,000",36, 125);
        g.drawString("9,500,000",42, 150);
        g.drawString("9,000,000",42, 175);
        g.drawString("8,500,000",42, 200);
        g.drawString("8,000,000",42, 225);
        g.drawString("7,500,000",42, 250);
        g.drawString("7,000,000",42, 275);
        g.drawString("6,500,000",42, 300);
        g.drawString("6,000,000",42, 325);
        g.drawString("5,500,000",42, 350);
        g.drawString("5,000,000",42, 375);
        g.drawString("4,500,000",42, 400);
        g.drawString("4,000,000",42, 425);
        g.drawString("3,500,000",42, 450);
        g.drawString("3,000,000",42, 475);
        g.drawString("2,500,000",42, 500);
        g.drawString("2,000,000",42, 525);
        g.drawString("1,500,000",42, 550);
        g.drawString("1,000,000",42, 575);
        g.drawString("500,000",50, 600);
        g.drawString("0",90, 625);
        
        g.setFont(new Font("TH SarabunPSK", Font.PLAIN, 18));
        g.setColor(Color.BLACK);
        g.drawString("0",90, 450);
        
        g.setFont(new Font("Angsana new", Font.BOLD, 20));
        g.drawString("ปี",520, 630);
        g.drawString("ยอดขาย",90, 95);
        
        g.setFont(new Font("TH SarabunPSK", Font.PLAIN, 18));
        g.drawString("2561",140, 650);
        g.drawString("2562",200, 650);
        g.drawString("2563",260, 650);
        g.drawString("2564",320, 650);
        g.drawString("2565",380, 650);
        g.drawString("2566",440, 650);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graphic 9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicTest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicTest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicTest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicTest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicTest3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
